columns:
  - width: 1/1
    fields:
      infoGettingStarted:
        label: Getting Started
        type: info
        text: |
          This is the starter kit you know and love. But now, each page template has a live preview of the page's content. It will update as you type!

          - **Unsaved Content**: See changes before saving
          - **Preview Links**: Internal links in the preview will open the corresponding Panel page
        theme: positive

  - width: 1/1
    sections:
      preview:
        label: Site Preview
        type: preview

  - width: 1/2
    sections:
      albums: sections/albums

  - width: 1/2
    sections:
      notes: sections/notes

      pages:
        type: pages
        create: default
        templates:
          - about
          - home
          - default
