columns:
  - width: 1/1
    fields:
      infoGettingStarted:
        label: Kirby Starterkit + Live Preview
        type: info
        text: |
          This is the sample site you know and love. But with a twist: **Each page template has a live preview** of the page's content. It updates as you type! This is meant to serve as an example of how Kirby Live Preview will work in your projects.

          Watch the magic happen as you click through the pages. Note the following features:

          - **Unsaved content**: See changes before they are saved.
          - **Panel redirects**: Site links in the preview will open the corresponding page in the Panel.
          - **Section behavior**: Place the preview section where you need it. It will match the surrounding layout.
        theme: positive

  - width: 1/1
    sections:
      preview:
        label: Site Preview
        type: preview

  - width: 1/2
    sections:
      albums: sections/albums

  - width: 1/2
    sections:
      notes: sections/notes

      pages:
        type: pages
        create: default
        templates:
          - about
          - home
          - default
